development:
  adapter: mysql
  encoding: utf8
  database: pc_development_rails3
  pool: 5
  username: rails_user
  password: rails_user

test:
  adapter: mysql
  encoding: utf8
  database: pc_testapp_test_rails3
  pool: 5
  username: rails_user
  password: rails_user

production:
  adapter: postgresql
  encoding: utf8
  database: pc_testapp_production_rails3
  pool: 5
  username: rails_user
  password: rails_user